export const linkTargets = {
  '.NET': 'https://dotnet.microsoft.com/en-us/',
  Apollo: 'https://apollographql.com/',
  CRDT: 'https://crdt.tech/',
  Fastify: 'https://fastify.dev/',
  Graphql: 'https://graphql.org/',
  Hypercore: 'https://github.com/holepunchto/hypercore',
  Javascript: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
  Neo4j: 'https://neo4j.com/',
  NodeJS: 'https://nodejs.org/',
  PostgreSQL: 'https://postgresql.org/',
  'React Native': 'https://reactnative.dev/',
  React: 'https://react.dev/',
  WebRTC: 'https://webrtc.org/',
  Yjs: 'https://github.com/yjs/yjs',
  Laravel: 'https://laravel.com/',
  PHP: 'https://php.net/',
  MySQL: 'https://www.mysql.com/',
};
